### ISSUE TITLE
Classe EntradaSaidaCadastroCandidatos

### ISSUE THREAD

**Issue by FernandoJean** [GuillhermeCunha/UrnaEletronica#5]
- Refatorar a estrutura de repetição com a sua condição de parada bem definida, armazenando a condição em uma constante. 
- Solicitar e armazenar corretamente o tipo de candidatura do candidato utilizando o Enum já criado. 
- Cadastrar os candidados inseridos no seu respectivo partido político. Obs: Para isso, deve-s e ter criar primeiramente o partido político para associar o candidato ao mesmo. 
- Cadastre os partidos políticos.

**Comment by GuillhermeCunha** [comment]
Fechando
